### ISSUE TITLE
KeyCloakAuthenticator: configurable certificate check

### ISSUE THREAD

**Issue by diocas** [swan-cern/jupyterhub-extensions#42]
Allow disabling the certificate check when contacting the idp (for local tests purposes only!)

**Comment by diocas** [comment]
@krishnan-r let's re-use the upstream authenticator config `tls_verify`

**Comment by krishnan-r** [comment]
We should use the upstream `fetch` method also because it is an async http client. `request.urlopen` would block the event loop for all other requests until we have a response. This might start giving timeouts when the rate of traffic to the hub is high and will slow down  other users requests.

Making it async also requires refactoring the logic, as we make a blocking request in `__init__` to fetch the configuration. I will look into this as a separate change as it needs more testing.
